doc: added references to penetration testing
sec-dev-iteso/secure-sdlc pull request #4
Opened 2023-08-23 02:42 UTC by danielrios-exe

[A](doc: added references to penetration testing)

2023-08-23 03:06 UTC, heryxpc reviewed
Este no lo habias mandado antes?

2023-08-23 03:08 UTC, danielrios-exe commented
> Este no lo habias mandado antes?

Noooo, es nuevo

2023-08-25 15:55 UTC, heryxpc commented on SecureSDLCNotes.md
> +[Core concepts of penetration testing][9]
Podrían agregar un nuevo parrafo a la sección de `## Penetration Testing`  donde describan los ` core concepts`. Creo la referencia es buena, pero no veo en que tecto acomodarla.

2023-08-25 15:56 UTC, heryxpc commented on SecureSDLCNotes.md
> +[10]: https://www.cloudflare.com/learning/security/glossary/what-is-penetration-testing/ 'What is penetration testing'[14]:https://owasp.org/www-community/OWASP_Risk_Rating_Methodology (OWASP Risk Ra
Aquí se les paso una nueva línea.

2023-08-25 15:57 UTC, heryxpc requested changes
Puse un par de comentarios extra, por si los pueden revisar.

2024-03-20 00:22 UTC, closed without merging